version: '3.8'

services:
  vital-chatwoot-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vital-chatwoot-bridge
    ports:
      - "8009:8009"
    environment:
      - CW_BRIDGE__app__port=8009
      - CW_BRIDGE__app__host=0.0.0.0
      - CW_BRIDGE__app__debug=false
      
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vital-bridge-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  vital-bridge-network:
    driver: bridge
