name: vital-chatwoot-bridge

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip=25.1
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.10.6
    - python-dotenv==1.0.0
    - PyYAML==6.0.1
